displayName=F2P StarHunt
author=Luis
support=https://github.com/pwatts6060/runelite-plugins/tree/star-info
description=Shares shooting star info with other miners
tags=star,shooting,mining,crashed
plugins=com.f2pstarhunt.F2PStarHuntPlugin